[workspace]
resolver = "2"

members = [
	"rush-core",
	"rush-cli",
	"rush-sdk",
	"rush-parser",
	"rush-visor",
	"rush-svm",
	"rush-svm/programs/rush-proxy",
	"rush-svm/programs/rush-store",
]

exclude = [
	"rush-sdk/examples/*"
]
