[workspace]
resolver = "2"

members = [
	"rush-ecs-core",
	"rush-ecs-cli",
	"rush-ecs-sdk",
	"rush-ecs-parser",
	"rush-ecs-visor",
	"rush-ecs-svm",
	"rush-ecs-keystore",
	"rush-ecs-manifest",
	"rush-ecs-svm/programs/rush-proxy",
	"rush-ecs-svm/programs/rush-store",
]

exclude = [
]
