[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "=2.0.5"

[lib]
name="hello"
crate-type = ["cdylib", "rlib"]

[workspace] # to exclude in virtual manifest
