[world]
name = "Dungeon World"
description = "This is a Dungeon world"
regions = ["dungeon"]

[dungeon]
player = [
	{ x = 0.0, y = 0.0, w = 32.0, h = 32.0, speed = 100.0, path = "farm/Player/Player.png" }
]
pot = [
	{ x = 0.0, y = 0.0, w = 32.0, h = 32.0, speed = 20.0, path = "dungeon/Objects/Pot.png" },
]
statue = [
	{ x = 6.0, y = 0.0, w = 32.0, h = 32.0, speed = 20.0, path = "dungeon/Objects/Statue.png" },
]
tomb = [
	{ x = -6.0, y = 0.0, w = 32.0, h = 32.0, speed = 20.0, path = "dungeon/Objects/Tomb.png" },
]
# animal = [
# 	{ x = 0.0, y = 0.0, w = 32.0, h = 32.0, speed = 20.0, path = "farm/Animals/Pig/Pig_01.png" },
# 	{ x = 0.0, y = 0.0, w = 32.0, h = 32.0, speed = 20.0, path = "farm/Animals/Pig/Pig_02.png" },
# 	{ x = 0.0, y = 0.0, w = 32.0, h = 32.0, speed = 20.0, path = "farm/Animals/Pig/Pig_03.png" },
# 	{ x = 0.0, y = 0.0, w = 32.0, h = 32.0, speed = 20.0, path = "farm/Animals/Pig/Pig_04.png" },
# 	{ x = 0.0, y = 0.0, w = 32.0, h = 32.0, speed = 20.0, path = "farm/Animals/Sheep/Sheep_01.png" },
# 	{ x = 0.0, y = 0.0, w = 32.0, h = 32.0, speed = 20.0, path = "farm/Animals/Sheep/Sheep_02.png" },
# 	{ x = 0.0, y = 0.0, w = 32.0, h = 32.0, speed = 20.0, path = "farm/Animals/Sheep/Sheep_03.png" },
# 	{ x = 0.0, y = 0.0, w = 32.0, h = 32.0, speed = 20.0, path = "farm/Animals/Sheep/Sheep_04.png" },
# 	{ x = 0.0, y = 0.0, w = 32.0, h = 32.0, speed = 20.0, path = "farm/Animals/Cow/Cow_01.png" },
# 	{ x = 0.0, y = 0.0, w = 32.0, h = 32.0, speed = 20.0, path = "farm/Animals/Cow/Cow_02.png" },
# 	{ x = 0.0, y = 0.0, w = 32.0, h = 32.0, speed = 20.0, path = "farm/Animals/Cow/Cow_03.png" },
# 	{ x = 0.0, y = 0.0, w = 32.0, h = 32.0, speed = 20.0, path = "farm/Animals/Cow/Cow_04.png" },
# 	{ x = 0.0, y = 0.0, w = 32.0, h = 32.0, speed = 20.0, path = "farm/Animals/Chicken/Chicken_01.png" },
# 	{ x = 0.0, y = 0.0, w = 32.0, h = 32.0, speed = 20.0, path = "farm/Animals/Chicken/Chicken_02.png" },
# 	{ x = 0.0, y = 0.0, w = 32.0, h = 32.0, speed = 20.0, path = "farm/Animals/Chicken/Chicken_03.png" },
# 	{ x = 0.0, y = 0.0, w = 32.0, h = 32.0, speed = 20.0, path = "farm/Animals/Chicken/Chicken_04.png" },
# 	{ x = 0.0, y = 0.0, w = 32.0, h = 32.0, speed = 20.0, path = "farm/Animals/Horse/Horse_01.png" }
# ]
