[package]
name = "rush-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.87"
rush-core = { version = "0.1.0", path = "../rush-core" }
rush-parser = { version = "0.1.0", path = "../rush-parser" }
thiserror = "1.0.63"

[[example]]
name = "bevy-apple-game"
path = "examples/bevy-apple-game/src/main.rs"

[[example]]
name = "bevy-farm-game"
path = "examples/bevy-farm-game/src/main.rs"

[[example]]
name = "bevy-platformer-game"
path = "examples/bevy-platformer-game/src/main.rs"
